// SPDX-License-Identifier: MIT
#pragma once

#include "orpheus/abi_version.h"
#include "treefall/namespace.h"

#define TREEFALL_ABI_MAJOR ORPHEUS_ABI_MAJOR
#define TREEFALL_ABI_MINOR ORPHEUS_ABI_MINOR
#define TREEFALL_ABI_EXPECT(x) ORPHEUS_ABI_EXPECT(x)
#define TREEFALL_ABI_V1_MAJOR ORPHEUS_ABI_V1_MAJOR
#define TREEFALL_ABI_V1_MINOR ORPHEUS_ABI_V1_MINOR
#define TREEFALL_ABI_CAP_NONE ORPHEUS_ABI_CAP_NONE

#define TREEFALL_SESSION_CAP_V1_CORE ORPHEUS_SESSION_CAP_V1_CORE
#define TREEFALL_CLIPGRID_CAP_V1_CORE ORPHEUS_CLIPGRID_CAP_V1_CORE
#define TREEFALL_CLIPGRID_CAP_V1_SCENES ORPHEUS_CLIPGRID_CAP_V1_SCENES
#define TREEFALL_RENDER_CAP_V1_CORE ORPHEUS_RENDER_CAP_V1_CORE
