// SPDX-License-Identifier: MIT
#pragma once

#include <stdint.h>

#define ORPHEUS_ABI_MAJOR 1
#define ORPHEUS_ABI_MINOR 0
#define ORPHEUS_ABI_EXPECT(x) ((x) == ORPHEUS_ABI_MAJOR)

#define ORPHEUS_ABI_V1_MAJOR ORPHEUS_ABI_MAJOR
#define ORPHEUS_ABI_V1_MINOR ORPHEUS_ABI_MINOR

#define ORPHEUS_ABI_CAP_NONE 0ull

#define ORPHEUS_SESSION_CAP_V1_CORE (1ull << 0)
#define ORPHEUS_CLIPGRID_CAP_V1_CORE (1ull << 0)
#define ORPHEUS_CLIPGRID_CAP_V1_SCENES (1ull << 1)
#define ORPHEUS_RENDER_CAP_V1_CORE (1ull << 0)
