name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --target track_playlist track_playlist_demo track_playlist_test
      - name: Collect plug-ins
        run: |
          mkdir -p plugins
          find build -type f \( -name '*.vst3' -o -name '*.dll' -o -name '*.so' -o -name '*.dylib' \) -exec cp {} plugins/ \;
      - name: Upload plug-ins
        uses: actions/upload-artifact@v4
        with:
          name: plugins-${{ matrix.os }}
          path: plugins
