name: Build
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install zlib (Ubuntu)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y zlib1g-dev
      - name: Install zlib (Windows)
        if: runner.os == 'Windows'
        run: choco install zlib -y --no-progress
      - name: Configure
        run: cmake -S . -B build -DORPHEUS_BUILD_REAPER_PLUGINS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Build
        run: cmake --build build --config RelWithDebInfo --parallel
