name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: build-and-test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Debug]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          extra=""
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            extra="-DCMAKE_OSX_ARCHITECTURES=arm64"
          fi
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            extra="${extra} -DORP_BUILD_SHARED_CORE=OFF"
          fi
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DORP_WITH_TESTS=ON \
            -DORP_BUILD_REAPER=ON \
            -DORP_BUILD_MINHOST=ON \
            ${extra}
        shell: bash

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.build_type }}

  perf-smoke:
    name: perf-smoke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build-perf -DCMAKE_BUILD_TYPE=Release -DENABLE_LTO=ON -DORP_WITH_TESTS=OFF -DORP_BUILD_REAPER=OFF -DORP_BUILD_MINHOST=OFF
        shell: bash

      - name: Build perf tools
        run: cmake --build build-perf --config Release --target orpheus_perf_render_click
        shell: bash

      - name: Perf smoke
        run: ./build-perf/tools/perf/orpheus_perf_render_click
        shell: bash
