name: Static
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  static-analysis:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Install analyzers (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck

      - name: Configure
        run: cmake -S . -B build-static -DORPHEUS_ENABLE_TESTS=OFF -DORPHEUS_BUILD_REAPER_PLUGINS=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: clang-tidy (non-blocking)
        shell: bash
        run: |
          if [ -f .github/scripts/run-clang-tidy.py ]; then
            python3 .github/scripts/run-clang-tidy.py build-static/compile_commands.json || true
          else
            echo "run-clang-tidy.py not present; skipping" | tee clangtidy.log
            clang-tidy --version || true
          fi

      - name: cppcheck (non-blocking)
        run: |
          cppcheck --enable=warning,style,performance,portability --project=build-static/compile_commands.json 2> cppcheck.log || true

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: static-logs
          path: |
            clangtidy.log
            cppcheck.log
          if-no-files-found: ignore
