name: Static

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck cmake build-essential

      - name: Configure build (RelWithDebInfo)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
          clang-tidy --version
          clang-tidy -p build $(find . -name '*.cpp' -o -name '*.cc' -o -name '*.cxx') \
            > clangtidy.log || true

      - name: Run cppcheck
        run: |
          cppcheck --version
          cppcheck --enable=all --inline-suppr --project=build/compile_commands.json \
            --output-file=cppcheck.log || true

      - name: Upload clang-tidy results
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-report
          path: clangtidy.log

      - name: Upload cppcheck results
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: cppcheck.log

