name: Static
on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: static-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install analyzers
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck
      - name: Configure
        run: cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DORPHEUS_BUILD_REAPER_PLUGINS=OFF
      - name: Run clang-tidy
        run: python run-clang-tidy.py -p build -header-filter '^sdk/.*' > clangtidy.log || true
      - name: Run cppcheck
        run: |
          cppcheck --project=build/compile_commands.json \
            --suppress=*:*WDL/* --suppress=*:*reaper-plugins/* --suppress=*:*build/* \
            --output-file=cppcheck.log || true
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: static-logs
          path: |
            clangtidy.log
            cppcheck.log
