/*
  ==============================================================================

    DesignTokens.h  —  GENERATED FILE. DO NOT EDIT BY HAND.

    Orpheus Design System tokens as C++ constants for the shmui JUCE layer.
    Generated by  apps/www/scripts/gen-juce-tokens.mts
    from          apps/www/styles/orpheus-tokens.css
    (canonical contract v0.2.0; orig. orpheus_design-system_2605, absorbed — see docs/shm/SHM008)

    To change a value: edit the design system, re-vendor the CSS, then run
      pnpm --filter=www gen:juce-tokens
    CI enforces that this file matches the CSS (check-juce-tokens.mts).

    source sha256: afe2ddc99fd81cdd4eefcdc0550af8919d25f711d72401a596036bc70744846a

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>

namespace shmui {
namespace tokens {

//==============================================================================
/** Lab palette (Freqfinder). */
namespace lab {
inline juce::Colour surface0() {
  return juce::Colour(0xFF07090D);
} // --lab-surface-0: #07090D
inline juce::Colour surface1() {
  return juce::Colour(0xFF0E131B);
} // --lab-surface-1: #0E131B
inline juce::Colour surface2() {
  return juce::Colour(0xFF151C27);
} // --lab-surface-2: #151C27
inline juce::Colour surface3() {
  return juce::Colour(0xFF1E2937);
} // --lab-surface-3: #1E2937
inline juce::Colour stroke() {
  return juce::Colour(0xFF2F3C4E);
} // --lab-stroke: #2F3C4E
inline juce::Colour text() {
  return juce::Colour(0xFFF4F7FB);
} // --lab-text: #F4F7FB
inline juce::Colour muted() {
  return juce::Colour(0xFF96A3B5);
} // --lab-muted: #96A3B5
inline juce::Colour shadow() {
  return juce::Colour(0xFF020305);
} // --lab-shadow: #020305
inline juce::Colour glare() {
  return juce::Colour::fromRGBA(255, 255, 255, 15);
} // --lab-glare: rgba(255, 255, 255, 0.06)
inline juce::Colour tone() {
  return juce::Colour(0xFF19E0B3);
} // --lab-tone: #19E0B3
inline juce::Colour odd() {
  return juce::Colour(0xFFFFAA5C);
} // --lab-odd: #FFAA5C
inline juce::Colour undertoneEven() {
  return juce::Colour(0xFF66B7FF);
} // --lab-undertone-even: #66B7FF
inline juce::Colour undertoneOdd() {
  return juce::Colour(0xFFAE7BFF);
} // --lab-undertone-odd: #AE7BFF
inline juce::Colour danger() {
  return juce::Colour(0xFFFF596A);
} // --lab-danger: #FF596A
inline juce::Colour warning() {
  return juce::Colour(0xFFFFC77A);
} // --lab-warning: #FFC77A
inline juce::Colour input() {
  return juce::Colour(0xFF8BCBFF);
} // --lab-input: #8BCBFF
inline juce::Colour overlay() {
  return juce::Colour(0xFFC79EFF);
} // --lab-overlay: #C79EFF
} // namespace lab

//==============================================================================
/** Console palette (Clip Composer). */
namespace console {
inline juce::Colour bg0() {
  return juce::Colour(0xFF0A1518);
} // --console-bg-0: #0a1518
inline juce::Colour bg1() {
  return juce::Colour(0xFF0F1F23);
} // --console-bg-1: #0f1f23
inline juce::Colour bg2() {
  return juce::Colour(0xFF17292F);
} // --console-bg-2: #17292f
inline juce::Colour bg3() {
  return juce::Colour(0xFF1F363C);
} // --console-bg-3: #1f363c
inline juce::Colour bgInset() {
  return juce::Colour(0xFF0C1A1E);
} // --console-bg-inset: #0c1a1e
inline juce::Colour warm0() {
  return juce::Colour(0xFF16120E);
} // --console-warm-0: #16120e
inline juce::Colour warm1() {
  return juce::Colour(0xFF1F1A14);
} // --console-warm-1: #1f1a14
inline juce::Colour warm2() {
  return juce::Colour(0xFF2A241A);
} // --console-warm-2: #2a241a
inline juce::Colour warm3() {
  return juce::Colour(0xFF3A3225);
} // --console-warm-3: #3a3225
inline juce::Colour warmInset() {
  return juce::Colour(0xFF1A1610);
} // --console-warm-inset: #1a1610
inline juce::Colour warmBorder() {
  return juce::Colour(0xFF4A4030);
} // --console-warm-border: #4a4030
inline juce::Colour cool0() {
  return juce::Colour(0xFF15181B);
} // --console-cool-0: #15181b
inline juce::Colour cool1() {
  return juce::Colour(0xFF1C2024);
} // --console-cool-1: #1c2024
inline juce::Colour cool2() {
  return juce::Colour(0xFF262B30);
} // --console-cool-2: #262b30
inline juce::Colour cool3() {
  return juce::Colour(0xFF353C42);
} // --console-cool-3: #353c42
inline juce::Colour coolInset() {
  return juce::Colour(0xFF181B1E);
} // --console-cool-inset: #181b1e
inline juce::Colour coolBorder() {
  return juce::Colour(0xFF3D464D);
} // --console-cool-border: #3d464d
inline juce::Colour metalLight() {
  return juce::Colour(0xFFA8A193);
} // --console-metal-light: #a8a193
inline juce::Colour metalMid() {
  return juce::Colour(0xFF6E6356);
} // --console-metal-mid: #6e6356
inline juce::Colour metalDark() {
  return juce::Colour(0xFF3D3A32);
} // --console-metal-dark: #3d3a32
inline juce::Colour metalWarm() {
  return juce::Colour(0xFF8A7558);
} // --console-metal-warm: #8a7558
inline juce::Colour greyLight() {
  return juce::Colour(0xFF9AA0A3);
} // --console-grey-light: #9aa0a3
inline juce::Colour greyMid() {
  return juce::Colour(0xFF5E6266);
} // --console-grey-mid: #5e6266
inline juce::Colour greyDark() {
  return juce::Colour(0xFF353A3E);
} // --console-grey-dark: #353a3e
inline juce::Colour walnut() {
  return juce::Colour(0xFF3A2820);
} // --console-walnut: #3a2820
inline juce::Colour tan() {
  return juce::Colour(0xFFC4A87A);
} // --console-tan: #c4a87a
inline juce::Colour cream() {
  return juce::Colour(0xFFEDE2CC);
} // --console-cream: #ede2cc
inline juce::Colour patina() {
  return juce::Colour(0xFF4A6B6F);
} // --console-patina: #4a6b6f
inline juce::Colour blue() {
  return juce::Colour(0xFF4D8B9E);
} // --console-blue: #4d8b9e
inline juce::Colour blueDark() {
  return juce::Colour(0xFF2F6A7D);
} // --console-blue-dark: #2f6a7d
inline juce::Colour amber() {
  return juce::Colour(0xFFD99450);
} // --console-amber: #d99450
inline juce::Colour amberGlow() {
  return juce::Colour(0xFFEBB06A);
} // --console-amber-glow: #ebb06a
inline juce::Colour green() {
  return juce::Colour(0xFF5FA572);
} // --console-green: #5fa572
inline juce::Colour orange() {
  return juce::Colour(0xFFC47540);
} // --console-orange: #c47540
inline juce::Colour coral() {
  return juce::Colour(0xFFB04848);
} // --console-coral: #b04848
inline juce::Colour text() {
  return juce::Colour(0xFFEDE2CC);
} // --console-text: #ede2cc
inline juce::Colour textMuted() {
  return juce::Colour(0xFF8A8276);
} // --console-text-muted: #8a8276
inline juce::Colour textDim() {
  return juce::Colour(0xFF5A5448);
} // --console-text-dim: #5a5448
inline juce::Colour border() {
  return juce::Colour(0xFF2D4A52);
} // --console-border: #2d4a52
} // namespace console

//==============================================================================
/** Clip state colors (Console button wells). */
namespace clip {
inline juce::Colour empty() {
  return juce::Colour(0xFF122024);
} // --clip-empty: #122024
inline juce::Colour loaded() {
  return juce::Colour(0xFF1F363C);
} // --clip-loaded: #1f363c
inline juce::Colour playing() {
  return juce::Colour(0xFF4A8A5A);
} // --clip-playing: #4a8a5a
inline juce::Colour cued() {
  return juce::Colour(0xFFC89456);
} // --clip-cued: #c89456
inline juce::Colour stopping() {
  return juce::Colour(0xFFB86838);
} // --clip-stopping: #b86838
} // namespace clip

//==============================================================================
/** Group / channel-strip colors. */
namespace group {
inline juce::Colour blue() {
  return juce::Colour(0xFF4D8B9E);
} // --group-blue: #4d8b9e
inline juce::Colour green() {
  return juce::Colour(0xFF4A8A5A);
} // --group-green: #4a8a5a
inline juce::Colour orange() {
  return juce::Colour(0xFFC47540);
} // --group-orange: #c47540
inline juce::Colour red() {
  return juce::Colour(0xFFB04848);
} // --group-red: #b04848
} // namespace group

//==============================================================================
/** Metering (shared across products). */
namespace meter {
inline juce::Colour green() {
  return juce::Colour(0xFF45A855);
} // --meter-green: #45a855
inline juce::Colour yellow() {
  return juce::Colour(0xFFC5A530);
} // --meter-yellow: #c5a530
inline juce::Colour orange() {
  return juce::Colour(0xFFC57030);
} // --meter-orange: #c57030
inline juce::Colour red() {
  return juce::Colour(0xFFB53535);
} // --meter-red: #b53535
} // namespace meter

//==============================================================================
/** Waveform (Clip Composer + FreqFinder). */
namespace wave {
inline juce::Colour trimIn() {
  return juce::Colour(0xFFFF00FF);
} // --wave-trim-in: #ff00ff
inline juce::Colour trimOut() {
  return juce::Colour(0xFF00FFFF);
} // --wave-trim-out: #00ffff
inline juce::Colour playhead() {
  return juce::Colour(0xFFFFFF00);
} // --wave-playhead: #ffff00
inline juce::Colour line() {
  return juce::Colour(0xFF4A9EFF);
} // --wave-line: #4a9eff
inline juce::Colour bg() {
  return juce::Colour(0xFF1A1A1A);
} // --wave-bg: #1a1a1a
} // namespace wave

//==============================================================================
/** Spacing scale (4px base). */
namespace space {
inline constexpr float _0 = 0.0f;   // --sp-0: 0
inline constexpr float _1 = 4.0f;   // --sp-1: 4px
inline constexpr float _2 = 8.0f;   // --sp-2: 8px
inline constexpr float _3 = 12.0f;  // --sp-3: 12px
inline constexpr float _4 = 16.0f;  // --sp-4: 16px
inline constexpr float _5 = 20.0f;  // --sp-5: 20px
inline constexpr float _6 = 24.0f;  // --sp-6: 24px
inline constexpr float _8 = 32.0f;  // --sp-8: 32px
inline constexpr float _10 = 40.0f; // --sp-10: 40px
inline constexpr float _12 = 48.0f; // --sp-12: 48px
inline constexpr float _16 = 64.0f; // --sp-16: 64px
} // namespace space

//==============================================================================
/** Corner radius. */
namespace radius {
inline constexpr float sm = 2.0f;     // --r-sm: 2px
inline constexpr float md = 4.0f;     // --r-md: 4px
inline constexpr float lg = 8.0f;     // --r-lg: 8px
inline constexpr float xl = 10.0f;    // --r-xl: 10px
inline constexpr float _2xl = 14.0f;  // --r-2xl: 14px
inline constexpr float _3xl = 20.0f;  // --r-3xl: 20px
inline constexpr float pill = 999.0f; // --r-pill: 999px
} // namespace radius

//==============================================================================
/** Border widths. */
namespace border {
inline constexpr float hair = 0.5f;  // --bw-hair: 0.5px
inline constexpr float thin = 1.0f;  // --bw-thin: 1px
inline constexpr float med = 1.5f;   // --bw-med: 1.5px
inline constexpr float thick = 3.0f; // --bw-thick: 3px
} // namespace border

//==============================================================================
/** Type scale (point sizes). */
namespace type {
inline constexpr float xs = 10.0f;   // --fs-xs: 10px
inline constexpr float sm = 12.0f;   // --fs-sm: 12px
inline constexpr float md = 14.0f;   // --fs-md: 14px
inline constexpr float lg = 16.0f;   // --fs-lg: 16px
inline constexpr float xl = 18.0f;   // --fs-xl: 18px
inline constexpr float _2xl = 21.0f; // --fs-2xl: 21px
inline constexpr float _3xl = 24.0f; // --fs-3xl: 24px
inline constexpr float _4xl = 32.0f; // --fs-4xl: 32px
inline constexpr float _5xl = 44.0f; // --fs-5xl: 44px
inline constexpr float _6xl = 64.0f; // --fs-6xl: 64px
} // namespace type

//==============================================================================
/** Motion — durations (ms) and cubic-bezier easing curves. */
namespace motion {
inline constexpr int fastMs = 120; // --dur-fast: 120ms
inline constexpr int baseMs = 200; // --dur-base: 200ms
inline constexpr int slowMs = 320; // --dur-slow: 320ms

/** Cubic-bezier control points (x1, y1, x2, y2). */
struct CubicBezier {
  float x1, y1, x2, y2;
};
inline constexpr CubicBezier out{0.32f, 0.72f, 0.32f,
                                 1.0f}; // --ease-out: cubic-bezier(0.32, 0.72, 0.32, 1)
inline constexpr CubicBezier inOut{0.65f, 0.0f, 0.35f,
                                   1.0f}; // --ease-in-out: cubic-bezier(0.65, 0, 0.35, 1)
inline constexpr CubicBezier meter{0.16f, 1.0f, 0.3f,
                                   1.0f}; // --ease-meter: cubic-bezier(0.16, 1, 0.30, 1)
} // namespace motion

} // namespace tokens
} // namespace shmui
