/*
  ==============================================================================

    DesignTokens.h  —  GENERATED FILE. DO NOT EDIT BY HAND.

    Orpheus Design System tokens as C++ constants for the shmui JUCE layer.
    Generated by  apps/www/scripts/gen-juce-tokens.mts
    from          apps/www/styles/orpheus-tokens.css
    (canonical contract v0.5.0; orig. orpheus_design-system_2605, absorbed — see docs/shm/SHM008)

    To change a value: edit apps/www/styles/orpheus-tokens.css, then run
      pnpm --filter=www gen:juce-tokens
    CI enforces that this file matches the CSS (check-juce-tokens.mts).

    source sha256: 2ea093c0ff0647833d37a81762c5fa6ac882a1cca7f86fefbc40e16b6443a8d9

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include <array>

namespace shmui {
namespace tokens {

//==============================================================================
/** Lab palette (Freqfinder). */
namespace lab {
inline juce::Colour surface0() {
  return juce::Colour(0xFF07090D);
} // --lab-surface-0: #07090d
inline juce::Colour surface1() {
  return juce::Colour(0xFF0E131B);
} // --lab-surface-1: #0e131b
inline juce::Colour surface2() {
  return juce::Colour(0xFF151C27);
} // --lab-surface-2: #151c27
inline juce::Colour surface3() {
  return juce::Colour(0xFF1E2937);
} // --lab-surface-3: #1e2937
inline juce::Colour stroke() {
  return juce::Colour(0xFF2F3C4E);
} // --lab-stroke: #2f3c4e
inline juce::Colour text() {
  return juce::Colour(0xFFF4F7FB);
} // --lab-text: #f4f7fb
inline juce::Colour muted() {
  return juce::Colour(0xFF96A3B5);
} // --lab-muted: #96a3b5
inline juce::Colour shadow() {
  return juce::Colour(0xFF020305);
} // --lab-shadow: #020305
inline juce::Colour glare() {
  return juce::Colour::fromRGBA(255, 255, 255, 15);
} // --lab-glare: rgba(255, 255, 255, 0.06)
inline juce::Colour tone() {
  return juce::Colour(0xFF19E0B3);
} // --lab-tone: #19e0b3
inline juce::Colour odd() {
  return juce::Colour(0xFFFFAA5C);
} // --lab-odd: #ffaa5c
inline juce::Colour undertoneEven() {
  return juce::Colour(0xFF66B7FF);
} // --lab-undertone-even: #66b7ff
inline juce::Colour undertoneOdd() {
  return juce::Colour(0xFFAE7BFF);
} // --lab-undertone-odd: #ae7bff
inline juce::Colour danger() {
  return juce::Colour(0xFFFF596A);
} // --lab-danger: #ff596a
inline juce::Colour warning() {
  return juce::Colour(0xFFFFC77A);
} // --lab-warning: #ffc77a
inline juce::Colour input() {
  return juce::Colour(0xFF8BCBFF);
} // --lab-input: #8bcbff
inline juce::Colour overlay() {
  return juce::Colour(0xFFC79EFF);
} // --lab-overlay: #c79eff
inline juce::Colour lightSurface0() {
  return juce::Colour(0xFFF4F7FB);
} // --lab-light-surface-0: #f4f7fb
inline juce::Colour lightSurface1() {
  return juce::Colour(0xFFEEF2F7);
} // --lab-light-surface-1: #eef2f7
inline juce::Colour lightSurface2() {
  return juce::Colour(0xFFFFFFFF);
} // --lab-light-surface-2: #ffffff
inline juce::Colour lightSurface3() {
  return juce::Colour(0xFFE4EAF1);
} // --lab-light-surface-3: #e4eaf1
inline juce::Colour lightStroke() {
  return juce::Colour(0xFFCDD6E1);
} // --lab-light-stroke: #cdd6e1
inline juce::Colour lightText() {
  return juce::Colour(0xFF07090D);
} // --lab-light-text: #07090d
inline juce::Colour lightMuted() {
  return juce::Colour(0xFF4A5666);
} // --lab-light-muted: #4a5666
inline juce::Colour lightTone() {
  return juce::Colour(0xFF0D8069);
} // --lab-light-tone: #0d8069
inline juce::Colour lightOdd() {
  return juce::Colour(0xFFA65316);
} // --lab-light-odd: #a65316
inline juce::Colour lightUndertoneEven() {
  return juce::Colour(0xFF176EA8);
} // --lab-light-undertone-even: #176ea8
inline juce::Colour lightUndertoneOdd() {
  return juce::Colour(0xFF7040B2);
} // --lab-light-undertone-odd: #7040b2
inline juce::Colour lightDanger() {
  return juce::Colour(0xFFB92F43);
} // --lab-light-danger: #b92f43
inline juce::Colour lightWarning() {
  return juce::Colour(0xFF8F6100);
} // --lab-light-warning: #8f6100
} // namespace lab

//==============================================================================
/** Console palette (Clip Composer). */
namespace console {
inline juce::Colour bg0() {
  return juce::Colour(0xFF071316);
} // --console-bg-0: #071316
inline juce::Colour bg1() {
  return juce::Colour(0xFF102329);
} // --console-bg-1: #102329
inline juce::Colour bg2() {
  return juce::Colour(0xFF1D353B);
} // --console-bg-2: #1d353b
inline juce::Colour bg3() {
  return juce::Colour(0xFF294950);
} // --console-bg-3: #294950
inline juce::Colour bgInset() {
  return juce::Colour(0xFF0D1B1D);
} // --console-bg-inset: #0d1b1d
inline juce::Colour warm0() {
  return juce::Colour(0xFF120E0F);
} // --console-warm-0: #120e0f
inline juce::Colour warm1() {
  return juce::Colour(0xFF21191D);
} // --console-warm-1: #21191d
inline juce::Colour warm2() {
  return juce::Colour(0xFF38282B);
} // --console-warm-2: #38282b
inline juce::Colour warm3() {
  return juce::Colour(0xFF49342B);
} // --console-warm-3: #49342b
inline juce::Colour warmInset() {
  return juce::Colour(0xFF150F0F);
} // --console-warm-inset: #150f0f
inline juce::Colour warmBorder() {
  return juce::Colour(0xFF4A4030);
} // --console-warm-border: #4a4030
inline juce::Colour cool0() {
  return juce::Colour(0xFF101418);
} // --console-cool-0: #101418
inline juce::Colour cool1() {
  return juce::Colour(0xFF211D21);
} // --console-cool-1: #211d21
inline juce::Colour cool2() {
  return juce::Colour(0xFF32281B);
} // --console-cool-2: #32281b
inline juce::Colour cool3() {
  return juce::Colour(0xFF493A28);
} // --console-cool-3: #493a28
inline juce::Colour coolInset() {
  return juce::Colour(0xFF15150F);
} // --console-cool-inset: #15150f
inline juce::Colour coolBorder() {
  return juce::Colour(0xFF3D464D);
} // --console-cool-border: #3d464d
inline juce::Colour surround() {
  return juce::Colour(0xFF060D0F);
} // --console-surround: #060d0f
inline juce::Colour warmSurround() {
  return juce::Colour(0xFF0D0A07);
} // --console-warm-surround: #0d0a07
inline juce::Colour coolSurround() {
  return juce::Colour(0xFF0C0F11);
} // --console-cool-surround: #0c0f11
inline juce::Colour fullscreenBg() {
  return juce::Colour(0xFF0B2427);
} // --console-fullscreen-bg: #0b2427
inline juce::Colour warmFullscreenBg() {
  return juce::Colour(0xFF2D1D25);
} // --console-warm-fullscreen-bg: #2d1d25
inline juce::Colour coolFullscreenBg() {
  return juce::Colour(0xFF0B111A);
} // --console-cool-fullscreen-bg: #0b111a
inline juce::Colour materialEdgeLight() {
  return juce::Colour(0xFFFFFFFF);
} // --console-material-edge-light: #ffffff
inline juce::Colour materialEdgeDark() {
  return juce::Colour(0xFF000000);
} // --console-material-edge-dark: #000000
inline juce::Colour materialContactShadow() {
  return juce::Colour(0xFF000000);
} // --console-material-contact-shadow: #000000
inline juce::Colour materialElevationShadow() {
  return juce::Colour(0xFF000000);
} // --console-material-elevation-shadow: #000000
inline juce::Colour materialGlare() {
  return juce::Colour(0xFFFFFFFF);
} // --console-material-glare: #ffffff
inline juce::Colour indicatorAmber() {
  return juce::Colour(0xFFFFB63F);
} // --console-indicator-amber: #ffb63f
inline juce::Colour indicatorAmberGlow() {
  return juce::Colour(0xFFFFD89F);
} // --console-indicator-amber-glow: #ffd89f
inline juce::Colour indicatorHealth() {
  return juce::Colour(0xFF75D18C);
} // --console-indicator-health: #75d18c
inline juce::Colour indicatorLoop() {
  return juce::Colour(0xFF5CB8FF);
} // --console-indicator-loop: #5cb8ff
inline juce::Colour indicatorCoral() {
  return juce::Colour(0xFFFF6267);
} // --console-indicator-coral: #ff6267
inline juce::Colour indicatorSpecular() {
  return juce::Colour(0xFFFFFFFF);
} // --console-indicator-specular: #ffffff
inline juce::Colour displaySurface() {
  return juce::Colour(0xFF27343A);
} // --console-display-surface: #27343a
inline juce::Colour displaySurfaceRaised() {
  return juce::Colour(0xFF34464A);
} // --console-display-surface-raised: #34464a
inline juce::Colour displayBorder() {
  return juce::Colour(0xFF6E817E);
} // --console-display-border: #6e817e
inline juce::Colour displayInk() {
  return juce::Colour(0xFFEAF6E5);
} // --console-display-ink: #eaf6e5
inline juce::Colour displayInkMuted() {
  return juce::Colour(0xFFA9BCB2);
} // --console-display-ink-muted: #a9bcb2
inline juce::Colour displayGrid() {
  return juce::Colour(0xFF596B6B);
} // --console-display-grid: #596b6b
inline juce::Colour displayMarker() {
  return juce::Colour(0xFFFFB63F);
} // --console-display-marker: #ffb63f
inline juce::Colour displaySelection() {
  return juce::Colour(0xFF65D5C5);
} // --console-display-selection: #65d5c5
inline juce::Colour displayGlare() {
  return juce::Colour(0xFFFFFFFF);
} // --console-display-glare: #ffffff
// --console-material-texture-style: powder-coat  (non-literal — not emitted)
// --console-material-texture-intensity: 40  (non-literal — not emitted)
// --console-material-texture-scale: 4px  (non-literal — not emitted)
// --console-warm-material-texture-style: bakelite-mottle  (non-literal — not emitted)
// --console-warm-material-texture-intensity: 60  (non-literal — not emitted)
// --console-warm-material-texture-scale: 24px  (non-literal — not emitted)
// --console-cool-material-texture-style: smooth-anodized  (non-literal — not emitted)
// --console-cool-material-texture-intensity: 0  (non-literal — not emitted)
// --console-cool-material-texture-scale: 0px  (non-literal — not emitted)
inline juce::Colour lightBg0() {
  return juce::Colour(0xFFE8EFEB);
} // --console-light-bg-0: #e8efeb
inline juce::Colour lightBg1() {
  return juce::Colour(0xFFDDE8E3);
} // --console-light-bg-1: #dde8e3
inline juce::Colour lightBg2() {
  return juce::Colour(0xFFF8FBF8);
} // --console-light-bg-2: #f8fbf8
inline juce::Colour lightBg3() {
  return juce::Colour(0xFFCEDCD5);
} // --console-light-bg-3: #cedcd5
inline juce::Colour lightBgInset() {
  return juce::Colour(0xFFD5E1DB);
} // --console-light-bg-inset: #d5e1db
inline juce::Colour lightText() {
  return juce::Colour(0xFF142422);
} // --console-light-text: #142422
inline juce::Colour lightTextMuted() {
  return juce::Colour(0xFF586B67);
} // --console-light-text-muted: #586b67
inline juce::Colour lightBorder() {
  return juce::Colour(0xFF9EB4AD);
} // --console-light-border: #9eb4ad
inline juce::Colour warmLight0() {
  return juce::Colour(0xFFF0EBE1);
} // --console-warm-light-0: #f0ebe1
inline juce::Colour warmLight1() {
  return juce::Colour(0xFFE5DCCD);
} // --console-warm-light-1: #e5dccd
inline juce::Colour warmLight2() {
  return juce::Colour(0xFFFAF7F0);
} // --console-warm-light-2: #faf7f0
inline juce::Colour warmLight3() {
  return juce::Colour(0xFFD6C8B4);
} // --console-warm-light-3: #d6c8b4
inline juce::Colour warmLightInset() {
  return juce::Colour(0xFFDDD1BF);
} // --console-warm-light-inset: #ddd1bf
inline juce::Colour warmLightText() {
  return juce::Colour(0xFF30271D);
} // --console-warm-light-text: #30271d
inline juce::Colour warmLightTextMuted() {
  return juce::Colour(0xFF716451);
} // --console-warm-light-text-muted: #716451
inline juce::Colour warmLightBorder() {
  return juce::Colour(0xFFAD9C82);
} // --console-warm-light-border: #ad9c82
inline juce::Colour coolLight0() {
  return juce::Colour(0xFFEDF0F1);
} // --console-cool-light-0: #edf0f1
inline juce::Colour coolLight1() {
  return juce::Colour(0xFFE2E7E9);
} // --console-cool-light-1: #e2e7e9
inline juce::Colour coolLight2() {
  return juce::Colour(0xFFFAFBFB);
} // --console-cool-light-2: #fafbfb
inline juce::Colour coolLight3() {
  return juce::Colour(0xFFD2DADD);
} // --console-cool-light-3: #d2dadd
inline juce::Colour coolLightInset() {
  return juce::Colour(0xFFDAE0E3);
} // --console-cool-light-inset: #dae0e3
inline juce::Colour coolLightText() {
  return juce::Colour(0xFF20272B);
} // --console-cool-light-text: #20272b
inline juce::Colour coolLightTextMuted() {
  return juce::Colour(0xFF5F6B72);
} // --console-cool-light-text-muted: #5f6b72
inline juce::Colour coolLightBorder() {
  return juce::Colour(0xFFAAB5BA);
} // --console-cool-light-border: #aab5ba
inline juce::Colour lightMaterialChassis() {
  return juce::Colour(0xFFB9C1B7);
} // --console-light-material-chassis: #b9c1b7
inline juce::Colour lightMaterialPanel() {
  return juce::Colour(0xFFA6B1A6);
} // --console-light-material-panel: #a6b1a6
inline juce::Colour lightMaterialRaised() {
  return juce::Colour(0xFFD4D9D2);
} // --console-light-material-raised: #d4d9d2
inline juce::Colour lightMaterialWell() {
  return juce::Colour(0xFFA0ACA2);
} // --console-light-material-well: #a0aca2
inline juce::Colour lightMaterialInset() {
  return juce::Colour(0xFF687770);
} // --console-light-material-inset: #687770
inline juce::Colour lightMaterialSeam() {
  return juce::Colour(0xFF626E65);
} // --console-light-material-seam: #626e65
inline juce::Colour lightMaterialSurround() {
  return juce::Colour(0xFF68736B);
} // --console-light-material-surround: #68736b
inline juce::Colour lightMaterialCapTop() {
  return juce::Colour(0xFFE2E5DF);
} // --console-light-material-cap-top: #e2e5df
inline juce::Colour lightMaterialCapBottom() {
  return juce::Colour(0xFF89968C);
} // --console-light-material-cap-bottom: #89968c
inline juce::Colour lightMaterialEdgeLight() {
  return juce::Colour(0xFFEEF0EA);
} // --console-light-material-edge-light: #eef0ea
inline juce::Colour lightMaterialEdgeDark() {
  return juce::Colour(0xFF59645C);
} // --console-light-material-edge-dark: #59645c
inline juce::Colour lightMaterialContactShadow() {
  return juce::Colour(0xFF293029);
} // --console-light-material-contact-shadow: #293029
inline juce::Colour lightMaterialElevationShadow() {
  return juce::Colour(0xFF1B211D);
} // --console-light-material-elevation-shadow: #1b211d
inline juce::Colour lightMaterialGlare() {
  return juce::Colour(0xFFF8F8F3);
} // --console-light-material-glare: #f8f8f3
inline juce::Colour lightTextSecondary() {
  return juce::Colour(0xFF2E382F);
} // --console-light-text-secondary: #2e382f
inline juce::Colour warmLightMaterialChassis() {
  return juce::Colour(0xFFC8B894);
} // --console-warm-light-material-chassis: #c8b894
inline juce::Colour warmLightMaterialPanel() {
  return juce::Colour(0xFFB9A475);
} // --console-warm-light-material-panel: #b9a475
inline juce::Colour warmLightMaterialRaised() {
  return juce::Colour(0xFFD9CBA9);
} // --console-warm-light-material-raised: #d9cba9
inline juce::Colour warmLightMaterialWell() {
  return juce::Colour(0xFFB39A6E);
} // --console-warm-light-material-well: #b39a6e
inline juce::Colour warmLightMaterialInset() {
  return juce::Colour(0xFF786C4C);
} // --console-warm-light-material-inset: #786c4c
inline juce::Colour warmLightMaterialSeam() {
  return juce::Colour(0xFF746347);
} // --console-warm-light-material-seam: #746347
inline juce::Colour warmLightMaterialSurround() {
  return juce::Colour(0xFF75654B);
} // --console-warm-light-material-surround: #75654b
inline juce::Colour warmLightMaterialCapTop() {
  return juce::Colour(0xFFE7DCC3);
} // --console-warm-light-material-cap-top: #e7dcc3
inline juce::Colour warmLightMaterialCapBottom() {
  return juce::Colour(0xFF958466);
} // --console-warm-light-material-cap-bottom: #958466
inline juce::Colour warmLightMaterialEdgeLight() {
  return juce::Colour(0xFFF4EAD4);
} // --console-warm-light-material-edge-light: #f4ead4
inline juce::Colour warmLightMaterialEdgeDark() {
  return juce::Colour(0xFF6D5D45);
} // --console-warm-light-material-edge-dark: #6d5d45
inline juce::Colour warmLightMaterialContactShadow() {
  return juce::Colour(0xFF352B1D);
} // --console-warm-light-material-contact-shadow: #352b1d
inline juce::Colour warmLightMaterialElevationShadow() {
  return juce::Colour(0xFF241C13);
} // --console-warm-light-material-elevation-shadow: #241c13
inline juce::Colour warmLightMaterialGlare() {
  return juce::Colour(0xFFFFF6E4);
} // --console-warm-light-material-glare: #fff6e4
inline juce::Colour warmLightTextSecondary() {
  return juce::Colour(0xFF3C2F1F);
} // --console-warm-light-text-secondary: #3c2f1f
inline juce::Colour coolLightMaterialChassis() {
  return juce::Colour(0xFFBFC3C1);
} // --console-cool-light-material-chassis: #bfc3c1
inline juce::Colour coolLightMaterialPanel() {
  return juce::Colour(0xFFAAB2B5);
} // --console-cool-light-material-panel: #aab2b5
inline juce::Colour coolLightMaterialRaised() {
  return juce::Colour(0xFFD5D9D8);
} // --console-cool-light-material-raised: #d5d9d8
inline juce::Colour coolLightMaterialWell() {
  return juce::Colour(0xFFA4AFB4);
} // --console-cool-light-material-well: #a4afb4
inline juce::Colour coolLightMaterialInset() {
  return juce::Colour(0xFF74867C);
} // --console-cool-light-material-inset: #74867c
inline juce::Colour coolLightMaterialSeam() {
  return juce::Colour(0xFF656D70);
} // --console-cool-light-material-seam: #656d70
inline juce::Colour coolLightMaterialSurround() {
  return juce::Colour(0xFF687073);
} // --console-cool-light-material-surround: #687073
inline juce::Colour coolLightMaterialCapTop() {
  return juce::Colour(0xFFE7E9E7);
} // --console-cool-light-material-cap-top: #e7e9e7
inline juce::Colour coolLightMaterialCapBottom() {
  return juce::Colour(0xFF858D8F);
} // --console-cool-light-material-cap-bottom: #858d8f
inline juce::Colour coolLightMaterialEdgeLight() {
  return juce::Colour(0xFFF8F9F7);
} // --console-cool-light-material-edge-light: #f8f9f7
inline juce::Colour coolLightMaterialEdgeDark() {
  return juce::Colour(0xFF596164);
} // --console-cool-light-material-edge-dark: #596164
inline juce::Colour coolLightMaterialContactShadow() {
  return juce::Colour(0xFF252B2D);
} // --console-cool-light-material-contact-shadow: #252b2d
inline juce::Colour coolLightMaterialElevationShadow() {
  return juce::Colour(0xFF171C1E);
} // --console-cool-light-material-elevation-shadow: #171c1e
inline juce::Colour coolLightMaterialGlare() {
  return juce::Colour(0xFFFFFFFF);
} // --console-cool-light-material-glare: #ffffff
inline juce::Colour coolLightTextSecondary() {
  return juce::Colour(0xFF30393D);
} // --console-cool-light-text-secondary: #30393d
// --console-light-material-texture-style: enamel-speckle  (non-literal — not emitted)
// --console-light-material-texture-intensity: 45  (non-literal — not emitted)
// --console-light-material-texture-scale: 3px  (non-literal — not emitted)
// --console-warm-light-material-texture-style: molded-abs  (non-literal — not emitted)
// --console-warm-light-material-texture-intensity: 75  (non-literal — not emitted)
// --console-warm-light-material-texture-scale: 18px  (non-literal — not emitted)
// --console-cool-light-material-texture-style: brushed-aluminum  (non-literal — not emitted)
// --console-cool-light-material-texture-intensity: 55  (non-literal — not emitted)
// --console-cool-light-material-texture-scale: 2px  (non-literal — not emitted)
inline juce::Colour lightFullscreenBg() {
  return juce::Colour(0xFF23383B);
} // --console-light-fullscreen-bg: #23383b
inline juce::Colour warmLightFullscreenBg() {
  return juce::Colour(0xFF34394A);
} // --console-warm-light-fullscreen-bg: #34394a
inline juce::Colour coolLightFullscreenBg() {
  return juce::Colour(0xFF3A302A);
} // --console-cool-light-fullscreen-bg: #3a302a
inline juce::Colour metalLight() {
  return juce::Colour(0xFFA8A193);
} // --console-metal-light: #a8a193
inline juce::Colour metalMid() {
  return juce::Colour(0xFF6E6356);
} // --console-metal-mid: #6e6356
inline juce::Colour metalDark() {
  return juce::Colour(0xFF3D3A32);
} // --console-metal-dark: #3d3a32
inline juce::Colour metalWarm() {
  return juce::Colour(0xFF8A7558);
} // --console-metal-warm: #8a7558
inline juce::Colour greyLight() {
  return juce::Colour(0xFF9AA0A3);
} // --console-grey-light: #9aa0a3
inline juce::Colour greyMid() {
  return juce::Colour(0xFF5E6266);
} // --console-grey-mid: #5e6266
inline juce::Colour greyDark() {
  return juce::Colour(0xFF353A3E);
} // --console-grey-dark: #353a3e
inline juce::Colour walnut() {
  return juce::Colour(0xFF3A2820);
} // --console-walnut: #3a2820
inline juce::Colour tan() {
  return juce::Colour(0xFFC4A87A);
} // --console-tan: #c4a87a
inline juce::Colour cream() {
  return juce::Colour(0xFFEDE2CC);
} // --console-cream: #ede2cc
inline juce::Colour patina() {
  return juce::Colour(0xFF4A6B6F);
} // --console-patina: #4a6b6f
inline juce::Colour blue() {
  return juce::Colour(0xFF4D8B9E);
} // --console-blue: #4d8b9e
inline juce::Colour blueDark() {
  return juce::Colour(0xFF2F6A7D);
} // --console-blue-dark: #2f6a7d
inline juce::Colour amber() {
  return juce::Colour(0xFFD99450);
} // --console-amber: #d99450
inline juce::Colour amberGlow() {
  return juce::Colour(0xFFEBB06A);
} // --console-amber-glow: #ebb06a
inline juce::Colour green() {
  return juce::Colour(0xFF5FA572);
} // --console-green: #5fa572
inline juce::Colour orange() {
  return juce::Colour(0xFFC47540);
} // --console-orange: #c47540
inline juce::Colour coral() {
  return juce::Colour(0xFFB04848);
} // --console-coral: #b04848
inline juce::Colour loop() {
  return juce::Colour(0xFF006AA7);
} // --console-loop: #006aa7
inline juce::Colour loopGlow() {
  return juce::Colour(0xFF008FD3);
} // --console-loop-glow: #008fd3
inline juce::Colour recordDormant() {
  return juce::Colour(0xFF6B5426);
} // --console-record-dormant: #6b5426
inline juce::Colour backDormant() {
  return juce::Colour(0xFFE8D89A);
} // --console-back-dormant: #e8d89a
inline juce::Colour signalPearl() {
  return juce::Colour(0xFFFAF5FF);
} // --console-signal-pearl: #faf5ff
inline juce::Colour signalLavender() {
  return juce::Colour(0xFFD1C2F7);
} // --console-signal-lavender: #d1c2f7
inline juce::Colour signalBlue() {
  return juce::Colour(0xFFCCE0FF);
} // --console-signal-blue: #cce0ff
inline juce::Colour lightSignalPearl() {
  return juce::Colour(0xFFB8C5C0);
} // --console-light-signal-pearl: #b8c5c0
inline juce::Colour lightSignalLavender() {
  return juce::Colour(0xFF827A99);
} // --console-light-signal-lavender: #827a99
inline juce::Colour lightSignalBlue() {
  return juce::Colour(0xFF527B87);
} // --console-light-signal-blue: #527b87
inline juce::Colour lightOperationAmber() {
  return juce::Colour(0xFFC5A530);
} // --console-light-operation-amber: #c5a530
inline juce::Colour lightOperationOrange() {
  return juce::Colour(0xFFB88A2B);
} // --console-light-operation-orange: #b88a2b
inline juce::Colour lightOperationSignalLavender() {
  return juce::Colour(0xFF8064A4);
} // --console-light-operation-signal-lavender: #8064a4
inline juce::Colour lightOperationTextOrange() {
  return juce::Colour(0xFF743F1C);
} // --console-light-operation-text-orange: #743f1c
inline juce::Colour lightBlue() {
  return juce::Colour(0xFF2F6A7D);
} // --console-light-blue: #2f6a7d
inline juce::Colour lightAmber() {
  return juce::Colour(0xFF9A5A25);
} // --console-light-amber: #9a5a25
inline juce::Colour lightGreen() {
  return juce::Colour(0xFF347347);
} // --console-light-green: #347347
inline juce::Colour lightOrange() {
  return juce::Colour(0xFF9B4F24);
} // --console-light-orange: #9b4f24
inline juce::Colour lightCoral() {
  return juce::Colour(0xFF9E3F3F);
} // --console-light-coral: #9e3f3f
inline juce::Colour text() {
  return juce::Colour(0xFFEDE2CC);
} // --console-text: #ede2cc
inline juce::Colour textMuted() {
  return juce::Colour(0xFF8A8276);
} // --console-text-muted: #8a8276
inline juce::Colour textDim() {
  return juce::Colour(0xFF5A5448);
} // --console-text-dim: #5a5448
inline juce::Colour border() {
  return juce::Colour(0xFF2D4A52);
} // --console-border: #2d4a52
} // namespace console

//==============================================================================
/** Clip state colors (Console button wells). */
namespace clip {
inline juce::Colour empty() {
  return juce::Colour(0xFF122024);
} // --clip-empty: #122024
inline juce::Colour loaded() {
  return juce::Colour(0xFF1F363C);
} // --clip-loaded: #1f363c
inline juce::Colour playing() {
  return juce::Colour(0xFF4A8A5A);
} // --clip-playing: #4a8a5a
inline juce::Colour cued() {
  return juce::Colour(0xFFC89456);
} // --clip-cued: #c89456
inline juce::Colour stopping() {
  return juce::Colour(0xFFB86838);
} // --clip-stopping: #b86838
} // namespace clip

//==============================================================================
/** Group / channel-strip colors. */
namespace group {
inline juce::Colour blue() {
  return juce::Colour(0xFF4D8B9E);
} // --group-blue: #4d8b9e
inline juce::Colour green() {
  return juce::Colour(0xFF4A8A5A);
} // --group-green: #4a8a5a
inline juce::Colour orange() {
  return juce::Colour(0xFFC47540);
} // --group-orange: #c47540
inline juce::Colour red() {
  return juce::Colour(0xFFB04848);
} // --group-red: #b04848
} // namespace group

//==============================================================================
/** Metering (shared across products). */
namespace meter {
inline juce::Colour green() {
  return juce::Colour(0xFF45A855);
} // --meter-green: #45a855
inline juce::Colour yellow() {
  return juce::Colour(0xFFC5A530);
} // --meter-yellow: #c5a530
inline juce::Colour orange() {
  return juce::Colour(0xFFC57030);
} // --meter-orange: #c57030
inline juce::Colour red() {
  return juce::Colour(0xFFB53535);
} // --meter-red: #b53535
inline juce::Colour safe() {
  return juce::Colour(0xFF45A855);
} // --meter-safe: #45a855
inline juce::Colour caution() {
  return juce::Colour(0xFFC5A530);
} // --meter-caution: #c5a530
inline juce::Colour warning() {
  return juce::Colour(0xFFC57030);
} // --meter-warning: #c57030
inline juce::Colour clip() {
  return juce::Colour(0xFFB53535);
} // --meter-clip: #b53535
inline juce::Colour surfaceLab() {
  return juce::Colour(0xFF0E131B);
} // --meter-surface-lab: #0e131b
inline juce::Colour peakLab() {
  return juce::Colour(0xFFF4F7FB);
} // --meter-peak-lab: #f4f7fb
inline juce::Colour surfaceConsole() {
  return juce::Colour(0xFF0C1A1E);
} // --meter-surface-console: #0c1a1e
inline juce::Colour peakConsole() {
  return juce::Colour(0xFFEBB06A);
} // --meter-peak-console: #ebb06a
inline juce::Colour surfaceLabLight() {
  return juce::Colour(0xFFEEF2F7);
} // --meter-surface-lab-light: #eef2f7
inline juce::Colour peakLabLight() {
  return juce::Colour(0xFF07090D);
} // --meter-peak-lab-light: #07090d
} // namespace meter

//==============================================================================
/** Waveform (Clip Composer + FreqFinder). */
namespace wave {
inline juce::Colour trimIn() {
  return juce::Colour(0xFFFF00FF);
} // --wave-trim-in: #ff00ff
inline juce::Colour trimOut() {
  return juce::Colour(0xFF00FFFF);
} // --wave-trim-out: #00ffff
inline juce::Colour playhead() {
  return juce::Colour(0xFFFFFF00);
} // --wave-playhead: #ffff00
inline juce::Colour line() {
  return juce::Colour(0xFF4A9EFF);
} // --wave-line: #4a9eff
inline juce::Colour bg() {
  return juce::Colour(0xFF1A1A1A);
} // --wave-bg: #1a1a1a
} // namespace wave

//==============================================================================
/** Semantic meter presentations shared by Lab and Console consumers. */
namespace meter {
struct Stop {
  float position;
  juce::Colour color;
};
struct Presentation {
  juce::Colour background;
  std::array<Stop, 4> stops;
  juce::Colour peak;
  juce::Colour clip;
};

inline Presentation labPresentation() {
  return {surfaceLab(),
          {{
              {0.0f, safe()},
              {0.65f, caution()},
              {0.85f, warning()},
              {1.0f, clip()},
          }},
          peakLab(),
          clip()};
}

inline Presentation consolePresentation() {
  return {surfaceConsole(),
          {{
              {0.0f, safe()},
              {0.65f, caution()},
              {0.85f, warning()},
              {1.0f, clip()},
          }},
          peakConsole(),
          clip()};
}

} // namespace meter

//==============================================================================
/** Mode × Console flavor semantic recipes. */
namespace console {
enum class AppearanceMode { Light, Dark };
enum class Flavor { Console, ConsoleWarm, ConsoleCool };
enum class MaterialTextureStyle {
  enamelSpeckle,
  moldedABS,
  brushedAluminum,
  powderCoat,
  bakeliteMottle,
  smoothAnodized,
};
struct MaterialTextureRecipe {
  MaterialTextureStyle style;
  float intensity;
  float scale;
};
struct MaterialRecipe {
  juce::Colour chassis, panel, raised, well, inset, seam, surround;
  juce::Colour capTop, capBottom, edgeLight, edgeDark;
  juce::Colour contactShadow, elevationShadow, glare;
  MaterialTextureRecipe texture;
};
struct IlluminationState {
  juce::Colour core, spill, border, foreground;
};
struct IlluminationRecipe {
  juce::Colour inactivePlastic;
  IlluminationState active, attention, fault;
};
struct DisplayPresentation {
  juce::Colour surface, raised, border, ink, inkMuted, grid, marker, selection, glare;
};
struct PhysicalControlRecipe {
  juce::Colour surface, bezel, face, highlight, shadow, metalLight, metalMid, metalDark, focusRing;
  float pressedOffset, disabledOpacity;
};
struct MeterPresentation {
  juce::Colour surface, text, tick, peak;
};
struct WaveformPresentation {
  juce::Colour background, grid, line, marker, selection;
};
struct Appearance {
  MaterialRecipe material;
  juce::Colour text, textMuted, textDim;
  IlluminationRecipe illumination;
  DisplayPresentation display;
  PhysicalControlRecipe physicalControl;
  MeterPresentation meter;
  WaveformPresentation waveform;
};

inline DisplayPresentation displayPresentation() {
  return {
      ::shmui::tokens::console::displaySurface(),  ::shmui::tokens::console::displaySurfaceRaised(),
      ::shmui::tokens::console::displayBorder(),   ::shmui::tokens::console::displayInk(),
      ::shmui::tokens::console::displayInkMuted(), ::shmui::tokens::console::displayGrid(),
      ::shmui::tokens::console::displayMarker(),   ::shmui::tokens::console::displaySelection(),
      ::shmui::tokens::console::displayGlare()};
}

inline IlluminationRecipe illuminationRecipe(const MaterialRecipe& material) {
  return {material.well,
          {::shmui::tokens::console::indicatorHealth(), ::shmui::tokens::console::indicatorHealth(),
           ::shmui::tokens::console::indicatorSpecular(), ::shmui::tokens::console::bg0()},
          {::shmui::tokens::console::indicatorAmber(),
           ::shmui::tokens::console::indicatorAmberGlow(),
           ::shmui::tokens::console::indicatorSpecular(), ::shmui::tokens::console::bg0()},
          {::shmui::tokens::console::indicatorCoral(), ::shmui::tokens::console::indicatorCoral(),
           ::shmui::tokens::console::indicatorSpecular(), ::shmui::tokens::console::bg0()}};
}

inline PhysicalControlRecipe physicalControlRecipe(const MaterialRecipe& material) {
  return {material.panel,
          material.inset,
          material.raised,
          material.edgeLight,
          material.elevationShadow,
          ::shmui::tokens::console::metalLight(),
          ::shmui::tokens::console::metalMid(),
          ::shmui::tokens::console::metalDark(),
          ::shmui::tokens::console::amberGlow(),
          1.0f,
          0.45f};
}

inline Appearance makeAppearance(const MaterialRecipe& material, juce::Colour text,
                                 juce::Colour textMuted, juce::Colour textDim,
                                 juce::Colour accent) {
  const auto display = displayPresentation();
  return {material,
          text,
          textMuted,
          textDim,
          illuminationRecipe(material),
          display,
          physicalControlRecipe(material),
          {material.inset, text, material.seam, display.ink},
          {display.surface, display.grid, accent, display.marker, display.selection}};
}

inline Appearance consoleLightAppearance() {
  const MaterialRecipe material{::shmui::tokens::console::lightMaterialChassis(),
                                ::shmui::tokens::console::lightMaterialPanel(),
                                ::shmui::tokens::console::lightMaterialRaised(),
                                ::shmui::tokens::console::lightMaterialWell(),
                                ::shmui::tokens::console::lightMaterialInset(),
                                ::shmui::tokens::console::lightMaterialSeam(),
                                ::shmui::tokens::console::lightMaterialSurround(),
                                ::shmui::tokens::console::lightMaterialCapTop(),
                                ::shmui::tokens::console::lightMaterialCapBottom(),
                                ::shmui::tokens::console::lightMaterialEdgeLight(),
                                ::shmui::tokens::console::lightMaterialEdgeDark(),
                                ::shmui::tokens::console::lightMaterialContactShadow(),
                                ::shmui::tokens::console::lightMaterialElevationShadow(),
                                ::shmui::tokens::console::lightMaterialGlare(),
                                {MaterialTextureStyle::enamelSpeckle, 0.045f, 3.0f}};
  return makeAppearance(material, ::shmui::tokens::console::lightText(),
                        ::shmui::tokens::console::lightTextSecondary(),
                        ::shmui::tokens::console::lightTextMuted(),
                        ::shmui::tokens::console::blue());
}

inline Appearance consoleWarmLightAppearance() {
  const MaterialRecipe material{::shmui::tokens::console::warmLightMaterialChassis(),
                                ::shmui::tokens::console::warmLightMaterialPanel(),
                                ::shmui::tokens::console::warmLightMaterialRaised(),
                                ::shmui::tokens::console::warmLightMaterialWell(),
                                ::shmui::tokens::console::warmLightMaterialInset(),
                                ::shmui::tokens::console::warmLightMaterialSeam(),
                                ::shmui::tokens::console::warmLightMaterialSurround(),
                                ::shmui::tokens::console::warmLightMaterialCapTop(),
                                ::shmui::tokens::console::warmLightMaterialCapBottom(),
                                ::shmui::tokens::console::warmLightMaterialEdgeLight(),
                                ::shmui::tokens::console::warmLightMaterialEdgeDark(),
                                ::shmui::tokens::console::warmLightMaterialContactShadow(),
                                ::shmui::tokens::console::warmLightMaterialElevationShadow(),
                                ::shmui::tokens::console::warmLightMaterialGlare(),
                                {MaterialTextureStyle::moldedABS, 0.075f, 18.0f}};
  return makeAppearance(material, ::shmui::tokens::console::warmLightText(),
                        ::shmui::tokens::console::warmLightTextSecondary(),
                        ::shmui::tokens::console::warmLightTextMuted(),
                        ::shmui::tokens::console::blue());
}

inline Appearance consoleCoolLightAppearance() {
  const MaterialRecipe material{::shmui::tokens::console::coolLightMaterialChassis(),
                                ::shmui::tokens::console::coolLightMaterialPanel(),
                                ::shmui::tokens::console::coolLightMaterialRaised(),
                                ::shmui::tokens::console::coolLightMaterialWell(),
                                ::shmui::tokens::console::coolLightMaterialInset(),
                                ::shmui::tokens::console::coolLightMaterialSeam(),
                                ::shmui::tokens::console::coolLightMaterialSurround(),
                                ::shmui::tokens::console::coolLightMaterialCapTop(),
                                ::shmui::tokens::console::coolLightMaterialCapBottom(),
                                ::shmui::tokens::console::coolLightMaterialEdgeLight(),
                                ::shmui::tokens::console::coolLightMaterialEdgeDark(),
                                ::shmui::tokens::console::coolLightMaterialContactShadow(),
                                ::shmui::tokens::console::coolLightMaterialElevationShadow(),
                                ::shmui::tokens::console::coolLightMaterialGlare(),
                                {MaterialTextureStyle::brushedAluminum, 0.055f, 2.0f}};
  return makeAppearance(material, ::shmui::tokens::console::coolLightText(),
                        ::shmui::tokens::console::coolLightTextSecondary(),
                        ::shmui::tokens::console::coolLightTextMuted(),
                        ::shmui::tokens::console::blue());
}

inline Appearance consoleDarkAppearance() {
  const MaterialRecipe material{::shmui::tokens::console::bg0(),
                                ::shmui::tokens::console::bg1(),
                                ::shmui::tokens::console::bg2(),
                                ::shmui::tokens::console::bg3(),
                                ::shmui::tokens::console::bgInset(),
                                ::shmui::tokens::console::border(),
                                ::shmui::tokens::console::surround(),
                                ::shmui::tokens::console::greyDark(),
                                ::shmui::tokens::console::bg2(),
                                ::shmui::tokens::console::materialEdgeLight(),
                                ::shmui::tokens::console::materialEdgeDark(),
                                ::shmui::tokens::console::materialContactShadow(),
                                ::shmui::tokens::console::materialElevationShadow(),
                                ::shmui::tokens::console::materialGlare(),
                                {MaterialTextureStyle::powderCoat, 0.04f, 4.0f}};
  return makeAppearance(material, ::shmui::tokens::console::text(),
                        ::shmui::tokens::console::textMuted(), ::shmui::tokens::console::textDim(),
                        ::shmui::tokens::console::blue());
}

inline Appearance consoleWarmDarkAppearance() {
  const MaterialRecipe material{::shmui::tokens::console::warm0(),
                                ::shmui::tokens::console::warm1(),
                                ::shmui::tokens::console::warm2(),
                                ::shmui::tokens::console::warm3(),
                                ::shmui::tokens::console::warmInset(),
                                ::shmui::tokens::console::warmBorder(),
                                ::shmui::tokens::console::warmSurround(),
                                ::shmui::tokens::console::greyDark(),
                                ::shmui::tokens::console::warm2(),
                                ::shmui::tokens::console::materialEdgeLight(),
                                ::shmui::tokens::console::materialEdgeDark(),
                                ::shmui::tokens::console::materialContactShadow(),
                                ::shmui::tokens::console::materialElevationShadow(),
                                ::shmui::tokens::console::materialGlare(),
                                {MaterialTextureStyle::bakeliteMottle, 0.06f, 24.0f}};
  return makeAppearance(material, ::shmui::tokens::console::text(),
                        ::shmui::tokens::console::textMuted(), ::shmui::tokens::console::textDim(),
                        ::shmui::tokens::console::blue());
}

inline Appearance consoleCoolDarkAppearance() {
  const MaterialRecipe material{::shmui::tokens::console::cool0(),
                                ::shmui::tokens::console::cool1(),
                                ::shmui::tokens::console::cool2(),
                                ::shmui::tokens::console::cool3(),
                                ::shmui::tokens::console::coolInset(),
                                ::shmui::tokens::console::coolBorder(),
                                ::shmui::tokens::console::coolSurround(),
                                ::shmui::tokens::console::greyDark(),
                                ::shmui::tokens::console::cool2(),
                                ::shmui::tokens::console::materialEdgeLight(),
                                ::shmui::tokens::console::materialEdgeDark(),
                                ::shmui::tokens::console::materialContactShadow(),
                                ::shmui::tokens::console::materialElevationShadow(),
                                ::shmui::tokens::console::materialGlare(),
                                {MaterialTextureStyle::smoothAnodized, 0.0f, 0.0f}};
  return makeAppearance(material, ::shmui::tokens::console::text(),
                        ::shmui::tokens::console::textMuted(), ::shmui::tokens::console::textDim(),
                        ::shmui::tokens::console::blue());
}

inline Appearance forProfile(Flavor flavor, AppearanceMode mode) {
  switch (flavor) {
  case Flavor::Console:
    return mode == AppearanceMode::Light ? consoleLightAppearance() : consoleDarkAppearance();
  case Flavor::ConsoleWarm:
    return mode == AppearanceMode::Light ? consoleWarmLightAppearance()
                                         : consoleWarmDarkAppearance();
  case Flavor::ConsoleCool:
    return mode == AppearanceMode::Light ? consoleCoolLightAppearance()
                                         : consoleCoolDarkAppearance();
  }
  return consoleLightAppearance();
}
} // namespace console

//==============================================================================
/** Spacing scale (4px base). */
namespace space {
inline constexpr float _0 = 0.0f;   // --sp-0: 0
inline constexpr float _1 = 4.0f;   // --sp-1: 4px
inline constexpr float _2 = 8.0f;   // --sp-2: 8px
inline constexpr float _3 = 12.0f;  // --sp-3: 12px
inline constexpr float _4 = 16.0f;  // --sp-4: 16px
inline constexpr float _5 = 20.0f;  // --sp-5: 20px
inline constexpr float _6 = 24.0f;  // --sp-6: 24px
inline constexpr float _8 = 32.0f;  // --sp-8: 32px
inline constexpr float _10 = 40.0f; // --sp-10: 40px
inline constexpr float _12 = 48.0f; // --sp-12: 48px
inline constexpr float _16 = 64.0f; // --sp-16: 64px
} // namespace space

//==============================================================================
/** Corner radius. */
namespace radius {
inline constexpr float sm = 2.0f;     // --r-sm: 2px
inline constexpr float md = 4.0f;     // --r-md: 4px
inline constexpr float lg = 8.0f;     // --r-lg: 8px
inline constexpr float xl = 10.0f;    // --r-xl: 10px
inline constexpr float _2xl = 14.0f;  // --r-2xl: 14px
inline constexpr float _3xl = 20.0f;  // --r-3xl: 20px
inline constexpr float pill = 999.0f; // --r-pill: 999px
} // namespace radius

//==============================================================================
/** Border widths. */
namespace border {
inline constexpr float hair = 0.5f;  // --bw-hair: 0.5px
inline constexpr float thin = 1.0f;  // --bw-thin: 1px
inline constexpr float med = 1.5f;   // --bw-med: 1.5px
inline constexpr float thick = 3.0f; // --bw-thick: 3px
} // namespace border

//==============================================================================
/** Type scale (point sizes). */
namespace type {
inline constexpr float xs = 10.0f;   // --fs-xs: 10px
inline constexpr float sm = 12.0f;   // --fs-sm: 12px
inline constexpr float md = 14.0f;   // --fs-md: 14px
inline constexpr float lg = 16.0f;   // --fs-lg: 16px
inline constexpr float xl = 18.0f;   // --fs-xl: 18px
inline constexpr float _2xl = 21.0f; // --fs-2xl: 21px
inline constexpr float _3xl = 24.0f; // --fs-3xl: 24px
inline constexpr float _4xl = 32.0f; // --fs-4xl: 32px
inline constexpr float _5xl = 44.0f; // --fs-5xl: 44px
inline constexpr float _6xl = 64.0f; // --fs-6xl: 64px
} // namespace type

//==============================================================================
/** Selector geometry. */
namespace selector {
inline constexpr float heightCompact = 24.0f;     // --selector-height-compact: 24px
inline constexpr float heightDefault = 32.0f;     // --selector-height-default: 32px
inline constexpr float heightComfortable = 40.0f; // --selector-height-comfortable: 40px
inline constexpr float paddingX = 8.0f;           // --selector-padding-x: 8px
inline constexpr float itemHeight = 28.0f;        // --selector-item-height: 28px
inline constexpr float menuMaxHeight = 280.0f;    // --selector-menu-max-height: 280px
} // namespace selector

//==============================================================================
/** Motion — durations (ms) and cubic-bezier easing curves. */
namespace motion {
inline constexpr int fastMs = 120; // --dur-fast: 120ms
inline constexpr int baseMs = 200; // --dur-base: 200ms
inline constexpr int slowMs = 320; // --dur-slow: 320ms

/** Cubic-bezier control points (x1, y1, x2, y2). */
struct CubicBezier {
  float x1, y1, x2, y2;
};
inline constexpr CubicBezier out{0.32f, 0.72f, 0.32f,
                                 1.0f}; // --ease-out: cubic-bezier(0.32, 0.72, 0.32, 1)
inline constexpr CubicBezier inOut{0.65f, 0.0f, 0.35f,
                                   1.0f}; // --ease-in-out: cubic-bezier(0.65, 0, 0.35, 1)
inline constexpr CubicBezier meter{0.16f, 1.0f, 0.3f,
                                   1.0f}; // --ease-meter: cubic-bezier(0.16, 1, 0.3, 1)
} // namespace motion

} // namespace tokens
} // namespace shmui
